version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: todoapp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: todoapp
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: